[package]
name = "perceptron"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
ndarray = "0.15.6"

[[bin]]
name = "perceptron"
path = "src/main.rs"

[[bin]]
name = "and_gate"
path = "src/bin/and_gate.rs"
